master-config:
  image: 192.168.99.1:5000/kiemsi/redis-replicas:v1
  command: master-config
  labels:
    io.rancher.container.start_once: true
    io.rancher.container.pull_image: always
master:
  restart: always
  image: 192.168.99.1:5000/kiemsi/redis-replicas:v1
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: master-config
    io.rancher.container.pull_image: always
  command: master
  volumes_from:
  - master-config


slave-config:
  image: 192.168.99.1:5000/kiemsi/redis-replicas:v1
  command: slave-config
  labels:
    io.rancher.container.start_once: true
    io.rancher.container.pull_image: always
slave:
  restart: always
  image: 192.168.99.1:5000/kiemsi/redis-replicas:v1
  command: slave
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: slave-config
    io.rancher.container.pull_image: always
  volumes_from:
  - slave-config
